[package]
name = "stormdl-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Core types and traits for StormDL"

[dependencies]
url.workspace = true
serde.workspace = true
thiserror.workspace = true
bytes.workspace = true
async-trait.workspace = true
